# Generated by Django 5.1.7 on 2026-04-17 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('Study', 'Study'), ('Health', 'Health'), ('Mindset', 'Mindset'), ('Routine', 'Routine')], default='Study', max_length=20)),
                ('cue', models.CharField(blank=True, max_length=160)),
                ('why', models.CharField(blank=True, max_length=220)),
                ('target_minutes', models.PositiveIntegerField(default=20)),
                ('difficulty_level', models.PositiveSmallIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('completions_count', models.PositiveIntegerField(default=0)),
                ('momentum_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('consistency_score', models.PositiveSmallIntegerField(default=0)),
                ('insight', models.CharField(blank=True, max_length=220)),
                ('last_completed_on', models.DateField(blank=True, null=True)),
                ('focus_mode', models.BooleanField(default=False)),
                ('recovery_mode', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-momentum_score', '-current_streak', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HabitBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=180)),
                ('icon', models.CharField(default='🏅', max_length=8)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('completed', models.BooleanField(default=False)),
                ('effort_score', models.PositiveSmallIntegerField(default=3)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('recovery_used', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='habits.habit')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('resilience_score', models.PositiveIntegerField(default=0)),
                ('last_activity_on', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habit_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('mood_score', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Steady'), (3, 'Good'), (4, 'Great'), (5, 'Peak')], default=3)),
                ('energy_score', models.PositiveSmallIntegerField(default=3)),
                ('stress_score', models.PositiveSmallIntegerField(default=3)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_archived'], name='habits_habi_user_id_76b3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'risk_score'], name='habits_habi_user_id_f599c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='habitbadge',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_e5e773_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['habit', 'completed'], name='habits_habi_habit_i_ed0784_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitcheckin',
            unique_together={('habit', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='moodlog',
            unique_together={('user', 'date')},
        ),
    ]
